/**
 * Shop definitions, item catalogs, and merchant constants.
 */
import type { ShopItem, ShopCategory } from '@/types/shop';

export const SHOP_INTERACTION_RADIUS = 8;
export const SHOP_SIGN_HEIGHT = 4.5;
export const SHOP_DEFAULT_WIDTH = 10;
export const SHOP_DEFAULT_DEPTH = 8;
export const SHOP_DEFAULT_HEIGHT = 5;

export const SHOP_CONFIG = {
  interactionRadius: SHOP_INTERACTION_RADIUS,
  signHeight: SHOP_SIGN_HEIGHT,
  defaultWidth: SHOP_DEFAULT_WIDTH,
  defaultDepth: SHOP_DEFAULT_DEPTH,
  defaultHeight: SHOP_DEFAULT_HEIGHT,
} as const;

export const SHOP_COLORS: Record<ShopCategory, string> = {
  convenienceStore: '#22aa44',
  gasStation: '#ff6600',
  coffeeShop: '#8B4513',
  restaurant: '#cc3333',
  shoppingMall: '#6633cc',
  garage: '#4488cc',
  restStop: '#339966',
};

export const SHOP_NAMES: Record<ShopCategory, string[]> = {
  convenienceStore: ['QuickMart', '7-Eleven', 'FamilyMart', 'Hi-Life', 'OK Mart'],
  gasStation: ['PetroMax', 'FuelUp', 'SpeedGas', 'EcoFuel', 'TurboGas'],
  coffeeShop: ['Bean & Brew', 'Café Rush', 'Daily Grind', 'Espresso Lane', 'Cup & Go'],
  restaurant: ['Highway Diner', 'Road Bowl', 'Burger Pit', 'Noodle Express', 'Steak Stop'],
  shoppingMall: ['Metro Mall', 'City Plaza', 'Grand Arcade', 'Shop Haven', 'Market Hub'],
  garage: ['Turbo Garage', 'Speed Shop', 'Drift Works', 'AutoCraft', 'Pit Stop Pro'],
  restStop: ['Rest Haven', 'Traveler\'s Inn', 'Highway Lodge', 'Pit Rest', 'Comfort Stop'],
};

export const ITEM_CATALOG: ShopItem[] = [
  /* ── Convenience Store ── */
  {
    id: 'energy_drink',
    name: 'Energy Drink',
    description: 'Boosts speed by 10% for 30 seconds.',
    price: 150,
    category: 'convenienceStore',
    itemType: 'drink',
    rarity: 'common',
    icon: '🥤',
    effects: [{ type: 'speedBoost', value: 0.1, duration: 30 }],
    stackable: true,
    maxStack: 10,
    levelRequirement: 1,
  },
  {
    id: 'snack_bar',
    name: 'Snack Bar',
    description: 'Restores 10 health points.',
    price: 80,
    category: 'convenienceStore',
    itemType: 'food',
    rarity: 'common',
    icon: '🍫',
    effects: [{ type: 'heal', value: 10, duration: 0 }],
    stackable: true,
    maxStack: 20,
    levelRequirement: 1,
  },
  {
    id: 'lucky_coin',
    name: 'Lucky Coin Charm',
    description: 'Doubles coin collection for 60 seconds.',
    price: 500,
    category: 'convenienceStore',
    itemType: 'consumable',
    rarity: 'uncommon',
    icon: '🪙',
    effects: [{ type: 'coinMultiplier', value: 2.0, duration: 60 }],
    stackable: true,
    maxStack: 5,
    levelRequirement: 3,
  },

  /* ── Gas Station ── */
  {
    id: 'fuel_can_small',
    name: 'Small Fuel Can',
    description: 'Refuels 25 units of fuel.',
    price: 200,
    category: 'gasStation',
    itemType: 'fuel',
    rarity: 'common',
    icon: '⛽',
    effects: [{ type: 'fuel', value: 25, duration: 0 }],
    stackable: true,
    maxStack: 5,
    levelRequirement: 1,
  },
  {
    id: 'fuel_can_large',
    name: 'Large Fuel Can',
    description: 'Refuels 50 units of fuel.',
    price: 350,
    category: 'gasStation',
    itemType: 'fuel',
    rarity: 'common',
    icon: '🛢️',
    effects: [{ type: 'fuel', value: 50, duration: 0 }],
    stackable: true,
    maxStack: 3,
    levelRequirement: 1,
  },
  {
    id: 'premium_fuel',
    name: 'Premium Fuel',
    description: 'Full refuel + 15% speed boost for 45 seconds.',
    price: 800,
    category: 'gasStation',
    itemType: 'fuel',
    rarity: 'uncommon',
    icon: '⚡',
    effects: [
      { type: 'fuel', value: 100, duration: 0 },
      { type: 'speedBoost', value: 0.15, duration: 45 },
    ],
    stackable: true,
    maxStack: 3,
    levelRequirement: 5,
  },

  /* ── Coffee Shop ── */
  {
    id: 'espresso',
    name: 'Double Espresso',
    description: 'Boosts XP gain by 50% for 120 seconds.',
    price: 250,
    category: 'coffeeShop',
    itemType: 'drink',
    rarity: 'common',
    icon: '☕',
    effects: [{ type: 'xpBoost', value: 1.5, duration: 120 }],
    stackable: true,
    maxStack: 5,
    levelRequirement: 1,
  },
  {
    id: 'latte',
    name: 'Caramel Latte',
    description: 'Restores 5 health and boosts XP by 25% for 60s.',
    price: 180,
    category: 'coffeeShop',
    itemType: 'drink',
    rarity: 'common',
    icon: '🥛',
    effects: [
      { type: 'heal', value: 5, duration: 0 },
      { type: 'xpBoost', value: 1.25, duration: 60 },
    ],
    stackable: true,
    maxStack: 10,
    levelRequirement: 1,
  },

  /* ── Restaurant ── */
  {
    id: 'burger_meal',
    name: 'Highway Burger Meal',
    description: 'Restores 30 health points.',
    price: 350,
    category: 'restaurant',
    itemType: 'food',
    rarity: 'common',
    icon: '🍔',
    effects: [{ type: 'heal', value: 30, duration: 0 }],
    stackable: true,
    maxStack: 5,
    levelRequirement: 1,
  },
  {
    id: 'steak_dinner',
    name: 'Premium Steak Dinner',
    description: 'Full health restore + 20% speed boost for 60s.',
    price: 1200,
    category: 'restaurant',
    itemType: 'food',
    rarity: 'rare',
    icon: '🥩',
    effects: [
      { type: 'heal', value: 100, duration: 0 },
      { type: 'speedBoost', value: 0.2, duration: 60 },
    ],
    stackable: true,
    maxStack: 3,
    levelRequirement: 5,
  },

  /* ── Garage ── */
  {
    id: 'repair_kit',
    name: 'Repair Kit',
    description: 'Repairs 40 health points.',
    price: 600,
    category: 'garage',
    itemType: 'tool',
    rarity: 'common',
    icon: '🔧',
    effects: [{ type: 'repair', value: 40, duration: 0 }],
    stackable: true,
    maxStack: 5,
    levelRequirement: 1,
  },
  {
    id: 'turbo_kit',
    name: 'Turbo Kit',
    description: 'Permanent +15% top speed when installed.',
    price: 8000,
    category: 'garage',
    itemType: 'vehiclePart',
    rarity: 'rare',
    icon: '🏎️',
    effects: [],
    stackable: false,
    maxStack: 1,
    levelRequirement: 5,
  },
  {
    id: 'nitro_tank',
    name: 'Nitro Tank',
    description: 'Extends boost duration by 50%.',
    price: 5000,
    category: 'garage',
    itemType: 'vehiclePart',
    rarity: 'uncommon',
    icon: '🔥',
    effects: [],
    stackable: false,
    maxStack: 1,
    levelRequirement: 3,
  },
  {
    id: 'sport_tires',
    name: 'Sport Tires',
    description: 'Improves handling and drift control by 20%.',
    price: 4000,
    category: 'garage',
    itemType: 'vehiclePart',
    rarity: 'uncommon',
    icon: '🛞',
    effects: [],
    stackable: false,
    maxStack: 1,
    levelRequirement: 3,
  },

  /* ── Shopping Mall ── */
  {
    id: 'neon_underglow',
    name: 'Neon Underglow Kit',
    description: 'Adds glowing underglow to your vehicle.',
    price: 3000,
    category: 'shoppingMall',
    itemType: 'cosmetic',
    rarity: 'uncommon',
    icon: '💡',
    effects: [],
    stackable: false,
    maxStack: 1,
    levelRequirement: 2,
  },
  {
    id: 'custom_horn',
    name: 'Custom Horn Pack',
    description: 'Unlocks 5 unique horn sounds.',
    price: 1500,
    category: 'shoppingMall',
    itemType: 'cosmetic',
    rarity: 'common',
    icon: '📯',
    effects: [],
    stackable: false,
    maxStack: 1,
    levelRequirement: 1,
  },

  /* ── Rest Stop ── */
  {
    id: 'travel_map',
    name: 'Regional Travel Map',
    description: 'Reveals all points of interest in nearby chunks.',
    price: 1000,
    category: 'restStop',
    itemType: 'tool',
    rarity: 'uncommon',
    icon: '🗺️',
    effects: [],
    stackable: false,
    maxStack: 1,
    levelRequirement: 2,
  },
  {
    id: 'first_aid_kit',
    name: 'First Aid Kit',
    description: 'Full health restore.',
    price: 900,
    category: 'restStop',
    itemType: 'consumable',
    rarity: 'uncommon',
    icon: '🩹',
    effects: [{ type: 'heal', value: 100, duration: 0 }],
    stackable: true,
    maxStack: 3,
    levelRequirement: 1,
  },
];

export const ITEM_CATALOG_MAP: Record<string, ShopItem> = Object.fromEntries(
  ITEM_CATALOG.map((item) => [item.id, item]),
);

export const SHOP_ITEM_ASSIGNMENTS: Record<ShopCategory, string[]> = {
  convenienceStore: ['energy_drink', 'snack_bar', 'lucky_coin'],
  gasStation: ['fuel_can_small', 'fuel_can_large', 'premium_fuel'],
  coffeeShop: ['espresso', 'latte'],
  restaurant: ['burger_meal', 'steak_dinner'],
  garage: ['repair_kit', 'turbo_kit', 'nitro_tank', 'sport_tires'],
  shoppingMall: ['neon_underglow', 'custom_horn'],
  restStop: ['travel_map', 'first_aid_kit'],
};
