/**
 * World generation and road network constants.
 */

export const WORLD = {
  CHUNK_SIZE: 100,
  RENDER_DISTANCE_CHUNKS: 5,
  UNLOAD_DISTANCE_CHUNKS: 7,
  MAX_ACTIVE_CHUNKS: 80,
  TERRAIN_Y: 0,
  FOG_NEAR: 60,
  FOG_FAR: 250,
  DAY_CYCLE_SPEED: 0.02,
  DEFAULT_SEED: 42,
} as const;

export const ROAD = {
  LANE_WIDTH: 3.8,
  SHOULDER_WIDTH: 2.5,
  MEDIAN_WIDTH: 1.5,
  BARRIER_HEIGHT: 0.9,
  BARRIER_WIDTH: 0.3,
  MARKING_WIDTH: 0.15,
  MARKING_DASH_LENGTH: 3.0,
  MARKING_GAP_LENGTH: 4.0,
  ROAD_THICKNESS: 0.15,
  SIDEWALK_WIDTH: 2.0,
  SIDEWALK_HEIGHT: 0.15,
  CURB_HEIGHT: 0.12,
} as const;

export const HIGHWAY = {
  LANES_PER_DIRECTION: 3,
  SPEED_LIMIT: 120,
  MIN_SEGMENT_LENGTH: 80,
  MAX_SEGMENT_LENGTH: 200,
  RAMP_LENGTH: 60,
  RAMP_CURVE_RADIUS: 40,
  ELEVATED_HEIGHT: 8,
  BRIDGE_PILLAR_SPACING: 20,
  BRIDGE_PILLAR_WIDTH: 1.2,
  TUNNEL_CLEARANCE: 5.5,
  TUNNEL_WALL_THICKNESS: 0.5,
  TOLL_BOOTH_WIDTH: 3.5,
  TOLL_BOOTH_DEPTH: 4,
  TOLL_BOOTH_HEIGHT: 3,
  SERVICE_AREA_LENGTH: 120,
  SERVICE_AREA_WIDTH: 60,
} as const;

export const CITY_ROAD = {
  LANES_PER_DIRECTION: 2,
  SPEED_LIMIT: 60,
  SEGMENT_LENGTH: 50,
  INTERSECTION_SIZE: 20,
  CROSSWALK_WIDTH: 3.5,
  TRAFFIC_LIGHT_HEIGHT: 5.5,
  TRAFFIC_LIGHT_POLE_RADIUS: 0.12,
} as const;

export const DECORATION = {
  STREET_LIGHT_SPACING: 25,
  STREET_LIGHT_HEIGHT: 7,
  STREET_LIGHT_ARM_LENGTH: 2.5,
  STREET_LIGHT_MAX_PER_CHUNK: 50,
  TREE_SPACING: 15,
  TREE_MIN_DISTANCE_FROM_ROAD: 5,
  BUILDING_MIN_DISTANCE_FROM_ROAD: 8,
  BUILDING_SPACING: 12,
  BILLBOARD_SPACING: 200,
  BILLBOARD_HEIGHT: 10,
  BILLBOARD_WIDTH: 8,
  SIGN_HEIGHT: 3,
  SKYLINE_DISTANCE: 400,
  SKYLINE_BUILDING_COUNT: 40,
} as const;

export const ZONE_DISTRIBUTION = {
  highway: 0.35,
  suburban: 0.25,
  cityCenter: 0.2,
  industrial: 0.1,
  countryside: 0.1,
} as const;
